apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stsf-other
  labels:
    app: stsf
spec:
  serviceName: stsf-service-other
  replicas: 2
  selector:
    matchLabels:
      app: stsf
  template:
    metadata:
      name: stsf
      labels:
        app: stsf
    spec:
      containers:
      - name: stsf-container
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80
        env:
          - name: VERSION
            value: V1
        volumeMounts:
        - name: nginx-local-claim
          mountPath: /usr/local/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-local-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
