apiVersion: v1
kind: Service
metadata:
  name: stsf-head
spec:
  #clusterIP: None
  selector:
    app: sts-head
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-head
  labels:
    app: sts-head
spec:
  serviceName: stsf-head
  replicas: 2
  selector:
    matchLabels:
      app: sts-head
  template:
    metadata:
      name: sts-head
      labels:
        app: sts-head
    spec:
      containers:
      - name: sts-head-container
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80