apiVersion: v1
kind: Pod
metadata:
  name: nslookup-stsf
  labels:
    app: nslookup
spec:
  containers:
  - name: nslookup-container
    image: busybox:1.37.0
    command: ['sh', '-c', 'nslookup stsf-service']
  restartPolicy: Never