apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        origin: cron
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            origin: cron-job
        spec:
          containers:
          - name: hello
            image: busybox:1.37.0
            args:
            - notworking
          restartPolicy: Never