apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2022-12-15T12:31:23Z"
  generation: 3
  name: hello
  namespace: default
  resourceVersion: "1203963"
  uid: e7faeca0-f56d-46dc-9598-bd999651844f
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        origin: cron
    spec:
      backoffLimit: 2
      template:
        metadata:
          creationTimestamp: null
          labels:
            origin: cron-job
        spec:
          containers:
          - args:
            - notworking
            image: busybox
            imagePullPolicy: Always
            name: hello
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: hello-27851802
    namespace: default
    resourceVersion: "1203962"
    uid: 1fd0e25a-4f87-4fa7-8d0f-9f0a4803f342
  lastScheduleTime: "2022-12-15T12:42:00Z"
