apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcreators.bash-operators.maque
spec:
  group: bash-operators.maque
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                createSvc:
                  type: string
                createPod:
                  type: string
                imageName:
                  type: string
  names:
    kind: PodCreator
    plural: podcreators
    shortNames:
    - pcs # check!
  scope: Namespaced