kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy.operator.binder
  namespace: default
subjects:
- kind: ServiceAccount
  name: deploy-creator-operator-account
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: deploy.operator.role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
