apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: benhall/nginx-with-curl
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: my-secret
      optional: false # default setting; "mysecret" must exist
      #items:
      #- key: user
      #  path: my-group/my-username