apiVersion: v1
kind: Pod
metadata:
  name: mypod-optional
spec:
  containers:
  - name: mypod
    image: nginx:alpine3.18    
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: my-secret
      optional: true
