services:
  web:
    volumes:
      - ./:/usr/share/nginx/html/
      #- type: bind
      #  source: ./index.htm 
      #  target: /usr/share/nginx/html/index.htm
    image: nginx:1.15.5
  python-redis:
    image: marcinmakowski/python-api:redis
    ports:
      - 5002:5002
    depends_on: 
      - redis
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
  redis:
    image: redis:5.0.10
