kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    ingress-ready: true
- role: worker
  labels:
    ingress-ready: true
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16