apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: conflict-b
  namespace: default
  labels:
    some: other-label
spec:
  replicas: 3
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [myapp]}
  template:
    metadata:
      name: myapp-pod-new
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: ewoutp/docker-nginx-curl
