allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
provisioner: example.com/external-nfs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
