apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0000
  labels:
    app: pv0000
spec:
  storageClassName: my-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs/general/00
    server: 192.168.0.2
  persistentVolumeReclaimPolicy: Recycle

