apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local01
  labels:
    app: local01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: my-storage-class
  selector:
    matchLabels:
      app: pv0000
