apiVersion: v1
kind: Pod
metadata:
  name: pod-nonroot
spec:
  securityContext:
    runAsNonRoot: true # will fail container if it starts with pid 0
  containers:
  - name: nonroot
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
