apiVersion: v1
kind: Pod
metadata:
  name: cant-read-vol-log
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000  # primary group ID  for all processes within any containers of the Pod
    fsGroup: 2000
  volumes:
  - name: read-vol-log
    hostPath:
      path:   /var/log/pods
      type: Directory # A directory must exist at the given path
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: read-vol-log
      mountPath:  /var/log/pods
      readOnly: true
    securityContext:
      runAsUser: 1000
