apiVersion: v1
kind: Pod
metadata:
  name: read-vol-log
spec:
  securityContext:
    fsGroup: 2000
    runAsUser: 0
    runAsGroup: 0
  volumes:
  - name: read-vol-log
    hostPath:
      path:   /var/log/pods
      type: Directory # A directory must exist at the given path
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: read-vol-log
      mountPath:  /var/log/pods
      readOnly: true
    securityContext:
      runAsUser: 1000
      runAsGroup: 0