apiVersion: v1
kind: Pod
metadata:
  name: pod-scx
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000  # primary group ID  for all processes within any containers of the Pod
    fsGroup: 2000  # group of mounted volume
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true # grants all of the system root’s capabilities
