apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false # indicates that the value of this PriorityClass should be used for Pods without a priorityClassName
description: "Some desc."
preemptionPolicy: Never # ahead of other pods, but not preempt current running