apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-high-priority
  labels:
    type: priority
spec:
  replicas: 1
  selector:
    matchLabels:
      type: priority
  template:
    metadata:
      name: pod-name
      labels:
        type: priority
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 2
          limits:
            cpu: 2
      priorityClassName: high-priority