apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  namespace: logging
  labels:
    k8s-app: filebeat
data:
  kubernetes.yml: |-
    - type: log
      paths:
      - /var/log/pods/**/*.log
      