apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-base
  namespace: default
  labels:
    company: sages
spec:
  replicas: 1
  selector:
    matchLabels:
      company: sages
  template:
    metadata:
      name: sages-pod2
      labels:
        company: sages
    spec:
      containers:
      - name: sages-container
        image: benhall/nginx-with-curl