apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-pod-anti-affinity
  labels:
    app: cache
spec:
  replicas: 3
  selector:
    matchLabels:
      distributed: cache
  template:
    metadata:
      name: cache1
      labels: 
        distributed: cache
    spec:
      affinity:
        podAntiAffinity: # don't run this pod on node on which pods are meeting requirement
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: distributed
                operator: In
                values:
                - cache
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cache
        image: busybox:1.37.0
        command: [ "sh", "-c", "sleep 1h" ]
