apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodename
  labels:
    app: nodename
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodename
  template:
    metadata:
      name: nodename-pod
      labels:
        app: nodename
    spec:
      nodeName: k8s-playground-worker
      containers:
      - name: nodename-container
        image: busybox:1.37.0
        command: ['sh', '-c', 'sleep 3600']
        resources:
          requests:
            cpu: 3
      restartPolicy: Always

