apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deployment
  labels:
    app: recreate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate
  template:
    metadata:
      name: recreate-pod
      labels:
        version: v3
        app: recreate
    spec:
      containers:
      - name: myapp-container
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80
        env:
          - name: VERSION
            value: V3
