apiVersion: v1
kind: Pod
metadata:
  name: pod-with-annotations
  labels:
    app: myapp
    type: server
  annotations:
    comes-from/file: file.txt
spec:
  containers:
  - name: myapp-container
    image: nginx:alpine3.18
