apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.37.0
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SERVICE_B
          valueFrom:
            configMapKeyRef:
              name: configuration
              key: service.json
      envFrom:
        - configMapRef:
            name: fromenv
  restartPolicy: Never