apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-items
spec:
  volumes:
    - name: servicejson
      configMap:
        name: configuration
        items:
        - key: service-b.config
          path: myconfig
  containers:
    - name: test-container
      image: ewoutp/docker-nginx-curl
      volumeMounts:
        - name: servicejson
          mountPath: /usr/local/nginx/html/ # this will remove any files in /usr/local/nginx/html/ folder and place configuration files
  restartPolicy: Never
