apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    node.type: nginx
  name: nginx
  namespace: app
spec:  
  replicas: 1
  selector:
    matchLabels:
      node.type: nginx
  template:
    metadata:
      labels:
        node.type: nginx
    spec: 
      securityContext: 
        runAsUser:  10001
        runAsGroup: 20001
        runAsNonRoot: true
      containers:
        - name: nginx  
          image: ewoutp/docker-nginx-curl
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            runAsUser:  30001
            runAsGroup: 40001
            #  Controls whether a process can gain more privileges than its parent process
            allowPrivilegeEscalation: false 
            readOnlyRootFilesystem: true
            seccompProfile:
              # https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
              type: RuntimeDefault # secure computing mode
            capabilities:
              # https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
                drop:
                  - ALL