apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    node.type: nginx-wrong
  name: nginx-wrong-user
  namespace: app
spec:  
  replicas: 1
  selector:
    matchLabels:
      node.type: nginx-wrong
  template:
    metadata:
      labels:
        node.type: nginx-wrong
    spec: 
      securityContext: 
        runAsUser:  10001
        runAsGroup: 20001
        runAsNonRoot: false
      containers:
        - name: nginx  
          image: nginx:1.15.5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: true 
            # readOnlyRootFilesystem: true # enforce an immutable infrastructure strategy
            capabilities:
                drop:
                  - all
                add:
                  - NET_BIND_SERVICE
                  - CHOWN
          volumeMounts:
          - mountPath: /var/cache/nginx
            name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}