apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: mydomain.com
    http:
      paths:
      - pathType: Prefix
        path: "/wordpress"
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
