apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      initContainers:
      - name: remove-lost-found
        image: busybox:1.28
        command: ['rm', '-rf', '/var/lib/mysql/lost+found']
        volumeMounts:
        - name: mysql-db
          mountPath: /var/lib/mysql
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
        env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
        volumeMounts:
        - name: mysql-db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi