kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: john-binding
subjects:
- kind: User
  name: john
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: ClusterRole
  name: john-role
  apiGroup: "rbac.authorization.k8s.io"