apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicate-my-app
  namespace: workshops
  labels:
    some: changed-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshops-myapp
  template:
    metadata:
      name: myapp-pod-new
      labels:
        app: workshops-myapp
    spec:
      containers:
      - name: myapp-container
        image: rlind/nginx:curl-latest
        env:
          - name: Test2
            value: Test