apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: ds
spec:
  minReadySeconds: 20
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2 # good for 0 downtime with update
  selector:
    matchLabels:
      app: ds
  template:
    metadata:
      name: ds-pod
      labels:
        app: ds
    spec:
      containers:
      - name: myapp-ds
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80
        env:
          - name: TEST
            value: TEST2

