apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: ds
spec:
  minReadySeconds: 5
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ds
  template:
    metadata:
      name: ds-pod
      labels:
        app: ds
    spec:
      containers:
      - name: myapp-ds
        image: nginx:alpine3.18
        ports:
          - containerPort: 80
        env:
          - name: TEST
            value: TEST2

