apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az01-clone
  labels:
    app: az01-clone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: az01
