FROM python:alpine3.17

RUN apk add --update curl && \
    rm -rf /var/cache/apk/*

RUN addgroup -S flaskuser && adduser -S flaskuser -G flaskuser
WORKDIR /usr/src/app
USER flaskuser

COPY python_backend/requirements.txt .

ENV PATH="${PATH}:/home/flaskuser/.local/bin"

RUN pip install --no-cache-dir -r requirements.txt

COPY python_backend/ .

ENV LOG_LEVEL=INFO
EXPOSE 5002

CMD [ "python", "main.py" ]
